# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7c390ed2d1982dae7b0a83c0ff7f1915be48b2c7bc9160a0376197bf44cbf9238fcda8bc31f0c5b56e2e0a7851304a26d3c6a392449082c47e5798d52e6c17

test:
  secret_key_base: 5042596d02d40360a3f3c83e758181136b6151635dd7ebe1a86eb1621585592339a06bcc803e74577cb693a54d2095d3f9a4fca9d1788e1c2a809ebe2ec7220c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
